---
- name: "Create influxdb datasource"
  tags: [stats]
  grafana_datasource:
    name: "{{datasource_name}}"
    grafana_url: "http://127.0.0.1:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    ds_type: "influxdb"
    url: "http://localhost:8086"
    database: "{{metrics_db_name}}"
    password: "{{metrics_db_password}}"
    user: "{{metrics_db_user}}"
    
- template:
    src: dashboard/apache.json
    dest: /tmp/apache.json
  tags: [stats]
  
- name: "Import grafana dashboard"
  tags: [stats, dashboard]
  grafana_dashboard:
    grafana_url: "http://127.0.0.1:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    state: present
    slug: apache
    message: Updated by ansible
    overwrite: yes
    path: /tmp/apache.json
  ignore_errors: yes