---
  - name: "Install telegraf"
    yum:
      name: "{{rpm_telegraf}}"

  - name: "Copy telegraf config"
    template:
      src: "{{telegraf_cfg_path}}"
      dest: "/etc/telegraf/telegraf.conf"

  - name: "Restart telegraf"
    service:
      name: telegraf
      state: restarted
      enabled: yes