---
 - name: "Install EPEL"
   yum:
     name: "{{EPEL_rpm}}"
     state: present
     
 - name: "Install nginx"
   yum:
     name: nginx
     state: present    
 
 - name: "Copy cfg into dest"
   template:
     src: load-balancer.conf
     dest: /etc/nginx/conf.d/load-balancer.conf
    
 - name: "Start nginx"
   service:
     name: "nginx"
     state: restarted