---
  - name: "Install EPEL from RPM"
    yum:
      name: "{{epel_repo}}"
      state: present
      
  - name: "Import EPEL GPG key"
    rpm_key:
      key: "{{epel_repo_gpg_key_url}}"
      state: present
     
  - name: "Install nginx"
    yum:
      name: nginx
      state: present    
    
  - name: "Start nginx"
    service:
      name: "nginx"
      state: restarted